spring.application.name=HSF_Project
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HSF_PROJECT;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Binh@261105
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
# Ép Spring phải chạy file data.sql SAU KHI Hibernate đã tạo bảng xong
#spring.jpa.defer-datasource-initialization=true
#
## Đảm bảo tính năng khởi tạo data từ file .sql luôn được bật
#spring.sql.init.mode=always
