package com.hsf_project.controller;

import com.hsf_project.entity.*;
import com.hsf_project.repository.*;
import jakarta.transaction.Transactional;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
import java.math.*;
import java.time.*;
import java.util.*;

@Controller @RequestMapping("/admin") @Transactional
public class AdminController {
    private static final List<String> ROOM_TYPES=List.of("2D","3D","IMAX"), SEAT_TYPES=List.of("STANDARD","VIP","COUPLE");
    private final CityRepository cities; private final CinemaRepository cinemas; private final CinemaRoomRepository rooms;
    private final SeatRepository seats; private final TicketRepository tickets; private final TicketPriceRepository prices;
    private final ComboRepository combos; private final BookingRepository bookings;
    public AdminController(CityRepository a,CinemaRepository b,CinemaRoomRepository c,SeatRepository d,TicketRepository e,TicketPriceRepository f,ComboRepository g,BookingRepository h){cities=a;cinemas=b;rooms=c;seats=d;tickets=e;prices=f;combos=g;bookings=h;}

    @GetMapping("/locations") public String locations(Model m){List<Cinema> cinemaList=cinemas.findByIsDeletedFalseOrderByNameAsc();Map<Integer,Long> cityCinemaCounts=new HashMap<>();cinemaList.forEach(x->cityCinemaCounts.merge(x.getCity().getId(),1L,Long::sum));m.addAttribute("cities",cities.findByIsDeletedFalseOrderByNameAsc());m.addAttribute("cinemas",cinemaList);m.addAttribute("cityCinemaCounts",cityCinemaCounts);m.addAttribute("rooms",rooms.findByIsDeletedFalseOrderByCinemaNameAscNameAsc());m.addAttribute("roomTypes",ROOM_TYPES);m.addAttribute("active","locations");return "admin/locations";}

    @PostMapping("/cities/save") public String saveCity(@RequestParam(required=false) Integer id,@RequestParam String name,RedirectAttributes ra){
        if(name.trim().isBlank())return err(ra,"Tên thành phố không được để trống","/admin/locations"); City x=id==null?new City():cities.findById(id).orElseThrow();x.setName(name.trim());x.setIsDeleted(false);cities.save(x);return ok(ra,"Đã lưu thành phố","/admin/locations");}
    @PostMapping("/cities/{id}/delete") public String delCity(@PathVariable Integer id,RedirectAttributes ra){if(cinemas.countByCityIdAndIsDeletedFalse(id)>0)return err(ra,"Không thể xóa thành phố đang có rạp hoạt động","/admin/locations");City x=cities.findById(id).orElseThrow();x.setIsDeleted(true);cities.save(x);return ok(ra,"Đã xóa thành phố","/admin/locations");}
    @PostMapping("/cinemas/save") public String saveCinema(@RequestParam(required=false) Integer id,@RequestParam String name,@RequestParam String address,@RequestParam Integer cityId,RedirectAttributes ra){if(name.isBlank()||address.isBlank())return err(ra,"Tên và địa chỉ rạp là bắt buộc","/admin/locations");Cinema x=id==null?new Cinema():cinemas.findById(id).orElseThrow();x.setName(name.trim());x.setAddress(address.trim());x.setCity(cities.findById(cityId).orElseThrow());x.setIsDeleted(false);cinemas.save(x);return ok(ra,"Đã lưu rạp chiếu","/admin/locations");}
    @PostMapping("/cinemas/{id}/delete") public String delCinema(@PathVariable Integer id,RedirectAttributes ra){if(rooms.countByCinemaIdAndIsDeletedFalse(id)>0)return err(ra,"Không thể xóa rạp đang có phòng hoạt động","/admin/locations");Cinema x=cinemas.findById(id).orElseThrow();x.setIsDeleted(true);cinemas.save(x);return ok(ra,"Đã xóa rạp","/admin/locations");}

    @PostMapping("/rooms/save") public String saveRoom(@RequestParam(required=false) Integer id,@RequestParam String name,@RequestParam String roomType,@RequestParam Integer totalSeats,@RequestParam Integer cinemaId,RedirectAttributes ra){
        if(!ROOM_TYPES.contains(roomType)||totalSeats<1||totalSeats>260||name.isBlank())return err(ra,"Thông tin phòng không hợp lệ (số ghế từ 1-260)","/admin/locations");CinemaRoom x=id==null?new CinemaRoom():rooms.findById(id).orElseThrow();boolean fresh=x.getId()==null;boolean capacityChanged=!fresh&&!Objects.equals(x.getTotalSeats(),totalSeats);if(capacityChanged&&tickets.countByTicketPriceRoomId(x.getId())>0)return err(ra,"Không thể đổi sức chứa vì phòng đã phát sinh vé","/admin/locations");x.setName(name.trim());x.setRoomType(roomType);x.setTotalSeats(totalSeats);x.setCinema(cinemas.findById(cinemaId).orElseThrow());x.setIsDeleted(false);rooms.save(x);
        if(fresh||capacityChanged){if(capacityChanged){List<Seat> old=seats.findByRoomIdAndIsDeletedFalseOrderByRowLabelAscSeatNumberAsc(x.getId());old.forEach(s->{s.setIsActive(false);s.setIsDeleted(true);});seats.saveAll(old);}createSeats(x,totalSeats);}if(fresh){for(String st:SEAT_TYPES){TicketPrice p=new TicketPrice();p.setRoom(x);p.setSeatType(st);p.setPrice(defaultPrice(roomType,st));p.setDeleted(false);prices.save(p);}}return ok(ra,"Đã lưu phòng chiếu"+((fresh||capacityChanged)?" và cập nhật sơ đồ ghế":""),"/admin/locations");}
    @PostMapping("/rooms/{id}/delete") public String delRoom(@PathVariable Integer id,RedirectAttributes ra){if(tickets.countByTicketPriceRoomId(id)>0)return err(ra,"Không thể xóa phòng đã phát sinh vé","/admin/locations");CinemaRoom x=rooms.findById(id).orElseThrow();x.setIsDeleted(true);rooms.save(x);return ok(ra,"Đã xóa phòng chiếu","/admin/locations");}

    @GetMapping("/ticket-prices") public String prices(Model m){Map<String,BigDecimal> matrix=new LinkedHashMap<>();for(String rt:ROOM_TYPES)for(String st:SEAT_TYPES){List<TicketPrice> list=prices.findByRoomRoomTypeAndSeatTypeAndIsDeletedFalse(rt,st);matrix.put(rt+"_"+st,list.isEmpty()?defaultPrice(rt,st):list.getFirst().getPrice());}m.addAttribute("matrix",matrix);m.addAttribute("roomTypes",ROOM_TYPES);m.addAttribute("seatTypes",SEAT_TYPES);m.addAttribute("active","prices");return "admin/ticket-prices";}
    @PostMapping("/ticket-prices") public String savePrices(@RequestParam Map<String,String> values,RedirectAttributes ra){for(String rt:ROOM_TYPES)for(String st:SEAT_TYPES){String key=rt+"_"+st;BigDecimal amount;try{amount=new BigDecimal(values.get(key));}catch(Exception e){return err(ra,"Giá "+rt+" / "+st+" không hợp lệ","/admin/ticket-prices");}if(amount.signum()<=0)return err(ra,"Giá vé phải lớn hơn 0","/admin/ticket-prices");for(CinemaRoom room:rooms.findByRoomTypeAndIsDeletedFalse(rt)){TicketPrice p=prices.findByRoomIdAndSeatTypeAndIsDeletedFalse(room.getId(),st).orElseGet(()->{TicketPrice n=new TicketPrice();n.setRoom(room);n.setSeatType(st);n.setDeleted(false);return n;});p.setPrice(amount);prices.save(p);}}return ok(ra,"Đã cập nhật đồng bộ 9 mức giá cho tất cả phòng","/admin/ticket-prices");}

    @GetMapping("/combos") public String combos(Model m){m.addAttribute("combos",combos.findByIsDeletedFalseOrderByIdDesc());m.addAttribute("active","combos");return "admin/combos";}
    @PostMapping("/combos/save") public String saveCombo(@RequestParam(required=false) Long id,@RequestParam String name,@RequestParam(required=false) String description,@RequestParam BigDecimal price,@RequestParam Integer quantity,@RequestParam String status,RedirectAttributes ra){if(name.isBlank()||price.signum()<=0||quantity<0||!List.of("ACTIVE","INACTIVE").contains(status))return err(ra,"Thông tin combo không hợp lệ","/admin/combos");Combo x=id==null?new Combo():combos.findById(id).orElseThrow();x.setName(name.trim());x.setDescription(description==null?"":description.trim());x.setPrice(price);x.setQuantity(quantity);x.setStatus(status);x.setIsDeleted(false);combos.save(x);return ok(ra,"Đã lưu combo","/admin/combos");}
    @PostMapping("/combos/{id}/delete") public String delCombo(@PathVariable Long id,RedirectAttributes ra){Combo x=combos.findById(id).orElseThrow();x.setIsDeleted(true);x.setStatus("INACTIVE");combos.save(x);return ok(ra,"Đã xóa combo","/admin/combos");}

    @GetMapping("/dashboard/{type}") public String dashboard(@PathVariable String type,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate from,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate to,Model m){if(!List.of("cinema","combo").contains(type))type="cinema";LocalDate end=to==null?LocalDate.now():to,start=from==null?end.minusDays(29):from;if(start.isAfter(end)){LocalDate q=start;start=end;end=q;}buildDashboard(type,bookings.findPaidInRange(start.atStartOfDay(),end.plusDays(1).atStartOfDay()),start,end,m);m.addAttribute("from",start);m.addAttribute("to",end);m.addAttribute("type",type);m.addAttribute("active","dashboard-"+type);return "admin/cinema-combo-dashboard";}
    private void buildDashboard(String type,List<Booking> paid,LocalDate from,LocalDate to,Model m){Map<LocalDate,BigDecimal> daily=new TreeMap<>();for(LocalDate d=from;!d.isAfter(to);d=d.plusDays(1))daily.put(d,BigDecimal.ZERO);Map<String,BigDecimal> revenue=new HashMap<>();Map<String,Long> volume=new HashMap<>();for(Booking b:paid){LocalDate day=b.getBookingDate().toLocalDate();if(type.equals("combo")){for(BookingCombo bc:b.getBookingCombos()){daily.merge(day,bc.getTotalPrice(),BigDecimal::add);revenue.merge(bc.getCombo().getName(),bc.getTotalPrice(),BigDecimal::add);volume.merge(bc.getCombo().getName(),bc.getQuantity().longValue(),Long::sum);}}else for(Ticket t:b.getTickets()){BigDecimal amount=t.getTicketPrice().getPrice();String name=t.getShowtime().getRoom().getCinema().getName();daily.merge(day,amount,BigDecimal::add);revenue.merge(name,amount,BigDecimal::add);volume.merge(name,1L,Long::sum);}}BigDecimal total=daily.values().stream().reduce(BigDecimal.ZERO,BigDecimal::add);long count=volume.values().stream().mapToLong(Long::longValue).sum();List<String> names=revenue.entrySet().stream().sorted(Map.Entry.<String,BigDecimal>comparingByValue().reversed()).map(Map.Entry::getKey).toList();m.addAttribute("totalRevenue",total);m.addAttribute("totalVolume",count);m.addAttribute("average",count==0?BigDecimal.ZERO:total.divide(BigDecimal.valueOf(count),0,RoundingMode.HALF_UP));m.addAttribute("chartLabels",daily.keySet().stream().map(LocalDate::toString).toList());m.addAttribute("chartValues",daily.values());m.addAttribute("rankNames",names);m.addAttribute("rankRevenue",revenue);m.addAttribute("rankVolume",volume);}
    private void createSeats(CinemaRoom room,int total){List<Seat> list=new ArrayList<>();for(int i=0;i<total;i++){int row=i/10;Seat s=new Seat();s.setRoom(room);s.setRowLabel(String.valueOf((char)('A'+row)));s.setSeatNumber(i%10+1);s.setSeatCode(s.getRowLabel()+s.getSeatNumber());s.setType(row>=Math.max(1,(total+9)/10-2)?"VIP":"STANDARD");s.setIsActive(true);s.setIsDeleted(false);list.add(s);}seats.saveAll(list);}
    private BigDecimal defaultPrice(String r,String s){int base=switch(r){case"3D"->90000;case"IMAX"->120000;default->70000;};int extra=switch(s){case"VIP"->20000;case"COUPLE"->70000;default->0;};return BigDecimal.valueOf(base+extra);}
    private String ok(RedirectAttributes r,String m,String p){r.addFlashAttribute("success",m);return"redirect:"+p;}private String err(RedirectAttributes r,String m,String p){r.addFlashAttribute("error",m);return"redirect:"+p;}
}
